# Generated by Django 2.2.17 on 2021-03-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pv',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
