# Generated by Django 2.2.17 on 2021-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='aaa', max_length=100, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
