# Generated by Django 2.2.17 on 2021-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210314_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(null=True, to='article.Tag', verbose_name='标签'),
        ),
    ]
