# Generated by Django 2.2.13 on 2021-03-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210314_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='article.Tag', verbose_name='标签'),
        ),
    ]
